version: "3.9"
services:

  redis:
    image: redis
    expose:
      - "6379"
    networks:
      - bookshelf

  mongo:
    image: mongo
    expose:
      - "27017"
    networks:
      - bookshelf

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8610:8610"
    depends_on:
      - redis
      - mongo
    networks:
      - bookshelf


networks:
  bookshelf:
